import "~/styles/globals.css"
import { Inter } from "next/font/google"

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata = {
  title: "Spotify Wrapped",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "https://open.spotifycdn.com/cdn/images/favicon.0f31d2ea.ico" }],
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable}`}>{children}</body>
    </html>
  )
}
